general[] = {
    {"ToolKit", 1},
    {"ItemMap", 1},
    {"ItemCompass", 1},
    {"ItemWatch", 1},
    {"Binocular", 1},
    {"HandGrenade", 1},
    {"MiniGrenade", 1},
    {"SmokeShell", 1},
    {"acc_flashlight", 1},
    {"acc_flashlight_pistol", 1},
    {"acc_flashlight_smg_01", 1},
    {"acc_pointer_IR", 5},
    {"arifle_TRG21_F", 1},
    {"arifle_Mk20_F", 3},
    {"arifle_Mk20_plain_F", 3},
    {"arifle_AKS_F", 4},
    {"arifle_SPAR_01_snd_F", 6},
    {"arifle_SPAR_01_blk_F", 6},
    {"arifle_SPAR_01_khk_F", 6},
    {"arifle_SDAR_F", 8},
    {"arifle_MX_F", 10},
    {"arifle_MX_khk_F", 10},
    {"arifle_MX_Black_F", 10},
    {"arifle_CTAR_hex_F", 15},
    {"arifle_CTAR_blk_F", 15},
    {"arifle_CTAR_ghex_F", 15},
    {"arifle_MSBS65_F", 16},
    {"arifle_MSBS65_sand_F", 16},
    {"arifle_MSBS65_camo_F", 16},
    {"arifle_MSBS65_black_F", 16},
    {"arifle_Katiba_F", 17},
    {"arifle_MSBS65_UBS_F", 19},
    {"arifle_MSBS65_UBS_black_F", 19},
    {"arifle_MSBS65_UBS_sand_F", 19},
    {"arifle_MSBS65_UBS_camo_F", 19},
    {"arifle_ARX_hex_F", 22},
    {"arifle_ARX_ghex_F", 22},
    {"arifle_ARX_blk_F", 22},
    {"arifle_AKM_F", 27},
    {"arifle_AK12_F", 33},
    {"arifle_AK12_lush_F", 33},
    {"arifle_AK12_arid_F", 33},
    {"10Rnd_50BW_Mag_F", 42},
    {"hgun_PDW2000_F", 1},
    {"sgun_HunterShotgun_01_sawedoff_F", 1},
    {"sgun_HunterShotgun_01_F", 2},
    {"SMG_01_F", 4},
    {"SMG_02_F", 7},
    {"SMG_05_F", 12},
    {"SMG_03_TR_khaki", 14},
    {"SMG_03_TR_black", 14},
    {"SMG_03_TR_camo", 14},
    {"SMG_03_TR_hex", 14},
    {"SMG_03_khaki", 15},
    {"SMG_03_black", 15},
    {"SMG_03_camo", 15},
    {"SMG_03_hex", 15},
    {"hgun_P07_F", 1},
    {"hgun_P07_khk_F", 1},
    {"hgun_P07_blk_F", 1},
    {"hgun_Rook40_F", 4},
    {"hgun_ACPC2_F", 9},
    {"hgun_Pistol_01_F", 12},
    {"hgun_Pistol_heavy_01_F", 14},
    {"hgun_Pistol_heavy_01_green_F", 14},
    {"hgun_Pistol_heavy_02_F", 18},
    {"optic_Holosight", 3},
    {"optic_Holosight_blk_F", 3},
    {"optic_Holosight_khk_F", 3},
    {"optic_Holosight_lush_F", 3},
    {"optic_Holosight_arid_F", 3},
    {"optic_Holosight_smg", 3},
    {"optic_Holosight_smg_blk_F", 3},
    {"optic_Holosight_smg_khk_F", 3},
    {"optic_Aco", 6},
    {"optic_Aco_smg", 6},
    {"optic_ACO_grn", 6},
    {"optic_ACO_grn_smg", 6},
    {"optic_MRCO", 9},
    {"optic_Hamr", 11},
    {"optic_Hamr_khk_F", 11},
    {"optic_Arco", 13},
    {"optic_Arco_blk_F", 13},
    {"optic_Arco_ghex_F", 13},
    {"optic_Arco_lush_F", 13},
    {"optic_Arco_arid_F", 13},
    {"optic_Arco_AK_blk_F", 13},
    {"optic_Arco_AK_lush_F", 13},
    {"optic_Arco_AK_arid_F", 13},
    {"optic_MRD", 14},
    {"optic_ERCO_blk_F", 15},
    {"optic_ERCO_khk_F", 15},
    {"optic_ERCO_snd_F", 15},
    {"optic_Yorris", 18},
    {"optic_NVS", 35},
    {"optic_Nightstalker", 45},
    {"bipod_01_F_snd", 16},
    {"bipod_01_F_blk", 16},
    {"bipod_01_F_mtp", 16},
    {"bipod_02_F_blk", 16},
    {"bipod_02_F_tan", 16},
    {"bipod_02_F_hex", 16},
    {"bipod_03_F_blk", 16},
    {"bipod_03_F_oli", 16},
    {"bipod_01_F_khk", 16},
    {"bipod_02_F_lush", 16},
    {"bipod_02_F_arid", 16}
};

grenadier[] = {
    {"arifle_SPAR_01_GL_snd_F", 20},
    {"arifle_Mk20_GL_F", 20},
    {"arifle_Mk20_GL_plain_F", 20},
    {"arifle_TRG21_GL_F", 20},
    {"arifle_MX_GL_F", 27},
    {"arifle_MX_GL_Black_F", 27},
    {"arifle_MX_GL_khk_F", 27},
    {"arifle_Katiba_GL_F", 32},
    {"arifle_CTAR_GL_hex_F", 32},
    {"arifle_CTAR_GL_blk_F", 32},
    {"arifle_CTAR_GL_ghex_F", 32},
    {"arifle_MSBS65_GL_F", 37},
    {"arifle_MSBS65_GL_black_F", 37},
    {"arifle_MSBS65_GL_sand_F", 37},
    {"arifle_AK12_GL_F", 43},
    {"arifle_AK12_GL_lush_F", 43},
    {"arifle_AK12_GL_arid_F", 43}
};

westGeneral[] = {
    {"U_B_CombatUniform_mcam", 1},
    {"U_B_Wetsuit", 5},
    {"V_TacVest_khk", 1},
    {"V_RebreatherB", 5},
    {"V_PlateCarrier1_rgr", 7},
    {"H_HelmetB_light_sand", 1},
    {"H_HelmetB_sand", 7},
    {"H_PilotHelmetFighter_B", 15},
    {"H_HelmetSpecB_sand", 25},
    {"B_AssaultPack_mcamo", 1},
    {"B_FieldPack_cbr", 5},
    {"B_TacticalPack_mcamo", 10},
    {"B_Kitbag_mcamo", 20},
    {"B_Carryall_mcamo", 30},
    {"B_Bergen_mcamo_F", 40},
    {"NVGoggles", 1},
    {"NVGogglesB_blk_F", 10},
    {"B_UavTerminal", 1}
};

westArmor[] = {
    {"V_PlateCarrierH_CTRG", 18},
    {"V_PlateCarrierGL_rgr", 30},
    {"U_O_V_Soldier_Viper_F", 40},
    {"H_HelmetO_ViperSP_ghex_F", 40},
    {"V_PlateCarrierSpec_rgr", 50}
};

eastGeneral[] = {
    {"B_AssaultPack_ocamo", 1},
    {"B_FieldPack_ocamo", 5},
    {"B_TacticalPack_ocamo", 10},
    {"B_Kitbag_cbr", 20},
    {"B_Carryall_ocamo", 30},
    {"B_Bergen_hex_F", 40},
    {"U_O_CombatUniform_ocamo", 1},
    {"U_O_Wetsuit", 5},
    {"H_HelmetO_ocamo", 1},
    {"H_HelmetSpecO_ocamo", 7},
    {"H_PilotHelmetFighter_O", 15},
    {"H_HelmetLeaderO_ocamo", 25},
    {"V_TacVest_brn", 1},
    {"V_RebreatherIR", 5},
    {"V_PlateCarrier1_rgr_noflag_F", 7},
    {"O_UavTerminal", 1},
    {"NVGoggles_OPFOR", 1},
    {"O_NVGoggles_hex_F", 10}
};

eastArmor[] = {
    {"V_PlateCarrier2_rgr_noflag_F", 18},
    {"V_PlateCarrierGL_rgr", 30},
    {"U_O_V_Soldier_Viper_hex_F", 40},
    {"H_HelmetO_ViperSP_hex_F", 40},
    {"V_PlateCarrierSpec_rgr", 50}
};

guerGeneral[] = {
    {"U_I_CombatUniform", 1},
    {"U_I_Wetsuit", 5},
    {"V_TacVest_camo", 1},
    {"V_RebreatherIA", 5},
    {"V_PlateCarrierIA2_dgtl", 7},
    {"H_HelmetIA", 1},
    {"H_PilotHelmetFighter_I", 15},
    {"B_AssaultPack_dgtl", 1},
    {"B_FieldPack_oli", 5},
    {"B_TacticalPack_oli", 10},
    {"B_Kitbag_cbr", 20},
    {"B_Carryall_oli", 30},
    {"B_Bergen_dgtl_F", 40},
    {"I_UavTerminal", 1},
    {"NVGoggles_INDEP", 1},
    {"NVGogglesB_blk_F", 10}
};

guerArmor[] = {
    {"V_PlateCarrier2_rgr", 18},
    {"V_PlateCarrierIAGL_dgtl", 30},
    {"U_O_V_Soldier_Viper_hex_F", 40},
    {"H_HelmetO_ViperSP_hex_F", 40},
    {"V_PlateCarrierSpec_rgr", 50}
};

launcher[] = {
    {"launch_RPG7_F", 15},
    {"RPG7_F", 15},
    {"launch_RPG32_F", 20},
    {"launch_RPG32_ghex_F", 20},
    {"launch_RPG32_green_F", 20},
    {"launch_RPG32_camo_F", 20},
    {"RPG32_F", 20},
    {"RPG32_HE_F", 20},
    {"launch_MRAWS_green_F", 25},
    {"launch_MRAWS_green_rail_F", 25},
    {"MRAWS_HEAT_F", 25},
    {"MRAWS_HE_F", 25},
    {"MRAWS_HEAT55_F", 25},
    {"launch_NLAW_F", 29},
    {"NLAW_F", 29},
    {"launch_B_Titan_F", 33},
    {"launch_O_Titan_F", 33},
    {"launch_I_Titan_F", 33},
    {"launch_B_Titan_short_F", 37},
    {"launch_O_Titan_short_F", 37},
    {"launch_I_Titan_short_F", 37},
    {"Titan_AA", 33},
    {"Titan_AT", 37},
    {"Titan_AP", 37},
    {"launch_O_Vorona_brown_F", 42},
    {"launch_O_Vorona_green_F", 42},
    {"Vorona_HEAT", 42}
};

marksman[] = {
    {"Rangefinder", 7},
    {"srifle_DMR_01_F", 7},
    {"arifle_MXM_F", 12},
    {"arifle_MXM_Black_F", 12},
    {"arifle_MXM_khk_F", 12},
    {"arifle_MSBS65_Mark_F", 17},
    {"arifle_MSBS65_Mark_black_F", 17},
    {"arifle_MSBS65_Mark_sand_F", 17},
    {"arifle_MSBS65_Mark_camo_F", 17},
    {"srifle_DMR_07_hex_F", 20},
    {"srifle_DMR_07_blk_F", 20},
    {"srifle_DMR_07_ghex_F", 20},
    {"srifle_LRR_camo_F", 24},
    {"srifle_LRR_F", 24},
    {"srifle_LRR_tna_F", 24},
    {"srifle_DMR_06_olive_F", 26},
    {"srifle_DMR_06_camo_F", 26},
    {"srifle_DMR_06_hunter_F", 26},
    {"srifle_EBR_F", 29},
    {"srifle_GM6_F", 32},
    {"srifle_GM6_camo_F", 32},
    {"srifle_GM6_ghex_F", 32},
    {"arifle_SPAR_03_khk_F", 35},
    {"arifle_SPAR_03_blk_F", 35},
    {"arifle_SPAR_03_snd_F", 35},
    {"srifle_DMR_04_Tan_F", 38},
    {"srifle_DMR_04_F", 38},
    {"srifle_DMR_03_F", 41},
    {"srifle_DMR_03_woodland_F", 41},
    {"srifle_DMR_03_khaki_F", 41},
    {"srifle_DMR_03_tan_F", 41},
    {"srifle_DMR_02_F", 43},
    {"srifle_DMR_02_camo_F", 43},
    {"srifle_DMR_02_sniper_F", 43},
    {"srifle_DMR_05_blk_F", 47},
    {"srifle_DMR_05_hex_F", 47},
    {"srifle_DMR_05_tan_f", 47},
    {"5Rnd_127x108_APDS_Mag", 50},
    {"optic_DMS_weathered_F", 17},
    {"optic_DMS", 19},
    {"optic_DMS_ghex_F", 19},
    {"optic_DMS_weathered_Kir_F", 19},
    {"optic_KHS_old", 21},
    {"optic_SOS", 23},
    {"optic_SOS_khk_F", 23},
    {"optic_KHS_blk", 25},
    {"optic_KHS_hex", 25},
    {"optic_KHS_tan", 25},
    {"optic_LRPS", 27},
    {"optic_LRPS_tna_F", 27},
    {"optic_LRPS_ghex_F", 27},
    {"optic_AMS", 33},
    {"optic_AMS_khk", 33},
    {"optic_AMS_snd", 33}
};

westMarksman[] = {
    {"U_B_GhillieSuit", 7},
    {"U_B_FullGhillie_lsh", 23},
    {"U_B_FullGhillie_sard", 23},
    {"U_B_FullGhillie_ard", 23}
};

eastMarksman[] = {
    {"U_O_GhillieSuit", 7},
    {"U_O_FullGhillie_lsh", 23},
    {"U_O_FullGhillie_sard", 23},
    {"U_O_FullGhillie_ard", 23}
};

guerMarksman[] = {
    {"U_I_GhillieSuit", 7},
    {"U_I_FullGhillie_lsh", 23},
    {"U_I_FullGhillie_sard", 23},
    {"U_I_FullGhillie_ard", 23}
};

machinegunner[] = {
    {"arifle_SPAR_02_snd_F", 10},
    {"arifle_SPAR_02_blk_F", 10},
    {"arifle_SPAR_02_khk_F", 10},
    {"LMG_03_F", 14},
    {"LMG_Mk200_F", 18},
    {"LMG_Mk200_black_F", 18},
    {"arifle_MX_SW_F", 23},
    {"arifle_MX_SW_Black_F", 23},
    {"arifle_MX_SW_khk_F", 23},
    {"arifle_CTARS_blk_F", 27},
    {"arifle_CTARS_hex_F", 27},
    {"arifle_CTARS_ghex_F", 27},
    {"LMG_Zafir_F", 32},
    {"arifle_RPK12_F", 39},
    {"arifle_RPK12_lush_F", 39},
    {"arifle_RPK12_arid_F", 39},
    {"MMG_02_camo_F", 51},
    {"MMG_02_black_F", 51},
    {"MMG_02_sand_F", 51},
    {"MMG_01_hex_F", 53},
    {"MMG_01_tan_F", 53}
};

suppressor[] = {
    {"muzzle_snds_58_blk_F", 25},
    {"muzzle_snds_58_wdm_F", 25},
    {"muzzle_snds_58_ghex_F", 25},
    {"muzzle_snds_58_hex_F", 25},
    {"muzzle_snds_L", 25},
    {"muzzle_snds_acp", 25},
    {"muzzle_snds_M", 25},
    {"muzzle_snds_m_khk_F", 25},
    {"muzzle_snds_m_snd_F", 25},
    {"muzzle_snds_B", 25},
    {"muzzle_snds_B_khk_F", 25},
    {"muzzle_snds_B_snd_F", 25},
    {"muzzle_snds_B_lush_F", 25},
    {"muzzle_snds_B_arid_F", 25},
    {"muzzle_snds_H", 25},
    {"muzzle_snds_H_MG", 25},
    {"muzzle_snds_H_SW", 25},
    {"muzzle_snds_H_khk_F", 25},
    {"muzzle_snds_H_snd_F", 25},
    {"muzzle_snds_H_MG_blk_F", 25},
    {"muzzle_snds_H_MG_khk_F", 25},
    {"muzzle_snds_570", 25},
    {"muzzle_snds_338_black", 43},
    {"muzzle_snds_338_green", 43},
    {"muzzle_snds_338_sand", 43},
    {"muzzle_snds_93mmg", 47},
    {"muzzle_snds_93mmg_tan", 47}
};